# Assignment Day 10:

## Question 1:

__*Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays__ 

In [1]:
import numpy as np

# Create two ndarrays which will be used to compare 
arr1 = np.array([10,23,54,89,45])
arr2 = np.array([12,34,32,77,22])

# Use .greater() method to perform greator than operation between two arrays
grt = np.greater(arr1,arr2)
print("Greator than :-",grt)

# Use .greater_equal() method to perform greator than and equal operation between two arrays
grt_eql = np.greater_equal(arr1,arr2)
print("Great than equal to :-",grt_eql)

# Use .less() method to perform less than operation between two arrays
less = np.less(arr1,arr2)
print("Less than :-",less)

# Use .less_equal() method to perform less than and equal operation between two arrays
less_eql = np.less_equal(arr1,arr2)
print("Less than equal to :-",less_eql)

Greator than :- [False False  True  True  True]
Great than equal to :- [False False  True  True  True]
Less than :- [ True  True False False False]
Less than equal to :- [ True  True False False False]


## Question 2:

__*Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives__

In [2]:
# create an array of 10 zeros
arr_zero = np.zeros(10)
print(arr_zero)

# create an array of 10 ones
arr_ones = np.ones(10)
print(arr_ones)

# create an array of 10 fives
arr_fives = np.full(10,5)
print(arr_fives)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]


## Question 3:

__*Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array__

In [3]:
# create an two-dimentional array

arr_to_sum = np.array([[1,2,3,4],[5,6,7,8],[10,22,65,11]])

# Sum of all elements
result = np.sum(arr_to_sum)
print("Sum of all elements :-",result)

# sum of the all elements column-wise
result1= np.sum(arr_to_sum,axis=0)
print("Column-wise :-",result1)

# sum of the all elements row-wise
result2 = np.sum(arr_to_sum,axis=1)
print("Row-wise:-",result2)

Sum of all elements :- 144
Column-wise :- [16 30 75 23]
Row-wise:- [ 10  26 108]


## Question 4:

__*Write a NumPy program to add, subtract, multiply, divide arguments element-wise__

In [4]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a2 = np.array([[9,13,11,21],[16,15,11,19]])

# add the corresponding elements of two arrays
addition = np.add(a1,a2)
print("Addition :-\n",addition)

# subtract the corresponding elements of two arrays
subtraction = np.subtract(a2,a1)
print("Subtraction :-\n",subtraction)

# multiply the corresponding elements of two arrays
multiplication = np.multiply(a1,a2)
print("Multiplication :-\n",multiplication)

# divide corresponding elements of two arrays
div = np.divide(a2,a1)
print("Division :-\n",div)

Addition :-
 [[10 15 14 25]
 [21 21 18 27]]
Subtraction :-
 [[ 8 11  8 17]
 [11  9  4 11]]
Multiplication :-
 [[  9  26  33  84]
 [ 80  90  77 152]]
Division :-
 [[9.         6.5        3.66666667 5.25      ]
 [3.2        2.5        1.57142857 2.375     ]]


## Question 5:

__*Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degree__

In [5]:
# Lets create an array of angles of which we will find sine, cosine and tangent 
val_in_deg = np.array([0,30,45,60,90])

# The above array values are in degrees but numpy's sine, cosine and tangent functions take values in radians

# So we need to convert these degrees into radians. To do so we will use .deg2rad() function 
val_in_rad = np.deg2rad(val_in_deg)

# Compute the values of sine at given angles
sin_val = np.sin(val_in_rad)
print("Sine :-",sin_val)

# Compute the values of cosine at given angles
cos_val = np.cos(val_in_rad)
print("\nCosine :-",cos_val)

# Compute the values of tangent at given angles
tan_val = np.tan(val_in_rad)
print("\nTangent :-",tan_val)


Sine :- [0.         0.5        0.70710678 0.8660254  1.        ]

Cosine :- [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]

Tangent :- [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


## Question 6:

__*Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels__

In [6]:
import pandas as pd

# Create a dictionary
dictionary1 = {"Name":["Noor", "Jocee Porter", "Joeel56", "Kixcodes"],
             "Age":[18, 25, 23, 24],
             "Domain":["AI engineer", "Backend developer", "Web developer", "AI engineer"],
             "Country":["India", "Russia", "Germany", "Germany"]}

# Now lets create a dataframe from the above dictionary

df = pd.DataFrame(dictionary1)
df

Name  Age             Domain  Country
0          Noor   18        AI engineer    India
1  Jocee Porter   25  Backend developer   Russia
2       Joeel56   23      Web developer  Germany
3      Kixcodes   24        AI engineer  Germany

## Question 7:

__*Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame__

In [7]:
# Create a dataframe which contains "Name" and "Score" column-names

df = pd.DataFrame({"Name":["Noor", "Jocee Porter", "Joeel56", "Kixcodes"],
                 "Age":[18,25,24,23],
                 "Country":["India", "Russia", "Germany", "Germany"],
                 "Score":[455,488,390,445]})

# To extract Name and Score columns we need to specify them between square brackets

df[["Name","Score"]]

Name  Score
0          Noor    455
1  Jocee Porter    488
2       Joeel56    390
3      Kixcodes    445

## Question 8:

__*Write a Pandas program to join the two given dataframes along rows and assign all data__

In [8]:
df1 = pd.DataFrame({"Name":["Noor", "Jocee Porter", "Joeel56"],
                 "Age":[18,25,24],
                 "Country":["India", "Russia", "Germany"],
                 "Score":[455,488,390]})

df2 = pd.DataFrame({"Name":["Martin","Kixcodes","Sallycodes"],
                   "Age":[28,25,27],
                    "Country":["America", "Germany", "Australia"],
                   "Score":[389,421,367]})

res = df1.merge(df2,how="outer")
res

Name  Age    Country  Score
0          Noor   18      India    455
1  Jocee Porter   25     Russia    488
2       Joeel56   24    Germany    390
3        Martin   28    America    389
4      Kixcodes   25    Germany    421
5    Sallycodes   27  Australia    367

## Question 9:

__*Write a Pandas program to detect missing values of a given DataFrame. Display True or False__

In [9]:
# Create a dataframe from  a dictionary which contains some missing values

df = pd.DataFrame({"Name":["Noor", "Jocee Porter", "Joeel56", np.nan],
             "Age":[18, 25, np.nan, 24],
             "Domain":[np.nan,"Backend developer", "Web developer", "AI engineer"],
             "Country":["India", np.nan, "Germany", "Germany"]})


# We use the .isnull() to find null missing values it will print True/False
df.isnull()


Name    Age  Domain  Country
0  False  False    True    False
1  False  False   False     True
2  False   True   False    False
3   True  False   False    False

## Question 10:

__* Write a Pandas program to create and display a one-dimensional array-like object containing an array of data__

In [11]:
# In pandas a one-dimensional array like object is called Series

arr = [130,189,234,245,123,456,765,190,123,998]

# We will use .Series() to convert this array into a Series

ser = pd.Series(arr)

print(type(ser))
ser

<class 'pandas.core.series.Series'>


0    130
1    189
2    234
3    245
4    123
5    456
6    765
7    190
8    123
9    998
dtype: int64